### ISSUE TITLE
How to mock Kotpref in tests

### ISSUE THREAD

**Issue by Drake1804** [chibatching/Kotpref#107]
I've tried to test method with Kotpref line `UserCredentialsPref.username` but I've always got same error java.lang.IllegalStateException: Kotpref has not been initialized.

**Comment by chibatching** [comment]
Hi,

I create sample test for KotprefModel object. Does this help you?

**Comment by Del-S** [comment]
Hi,

It works for me based on #110 but it does not seem to mock default values (String for example). Is that intentional? I can set them manually in the test but I was wondering if it could return default values instead of nulls. :)

Thanks for the info.
