### ISSUE TITLE
How to clear pref ?

### ISSUE THREAD

**Issue by cahyofendhi** [chibatching/Kotpref#117]
i want to clear all data saved in pref, how to do it ?

**Comment by chibatching** [comment]
Use clear() function.

If you have kotpref model object like below,
```kotlin
object FooPref : KotprefModel {
  var bar: String by stringPref()
}
```

you can clear data following instruction. 

```kotlin
FooPref.clear()
```

**Comment by cahyofendhi** [comment]
thanks
