### ISSUE TITLE
Is there any method to clear All saved preferences?

### ISSUE THREAD

**Issue by tapanInexture** [chibatching/Kotpref#123]
Just wondering If any method you can provide from which I can remove all saved preference values?
Thanks, Your library is Awesome!!

**Comment by chibatching** [comment]
If you want to clear preferences related to each KotprefModel, you can do with #117.
But if you wanna remove preferences of all your KotprefModels, the way is not provided by Kotpref.

You may be able to remove all preferences file just deleting directory `/data/data/{your.application.package}/shared_prefs`.
But in this directory, the other libraries or SDKs preferences may exist, you should do it very carefully.
