### ISSUE TITLE
Make clear() method open

### ISSUE THREAD

**Issue by vitorhugods** [chibatching/Kotpref#149]
As stated in the title.

I'm trying to perform a verification/assertion on the `clear()` method of a `KotprefModel`, and right now I have no way of doing so.

I don't think there are no drawbacks in opening the method, as I couldn't find any internal usage of the method.

Thanks again for the great library and support you are giving =)

**Comment by ITurchenko** [comment]
+1

In my case I need calling blockingCommitBulkEdit() instead of commitBulkEdit()
