### ISSUE TITLE
How to use Map with gsonPref

### ISSUE THREAD

**Issue by nksaroj** [chibatching/Kotpref#164]
```
class ProductLocal(context: Context) : KotprefModel() {
    var productMap by gsonPref(HashMap<String,String>())
    var productContentsMap by gsonPref(ConcurrentHashMap<String,String>())

}
```
I have tried both and none of them works. Am I missing anything here?

  productLocal.productContentsMap.putAll (<map data>)

**Comment by chibatching** [comment]
`putAll` and other mutation operation affect only the deserialized object. 
If you want to save into preferences, you have to put back value to KotprefModel.

```kotlin
val contentsMap = productLocal.productContentsMap
contentsMap.putAll(someMap)
productLocal.productContentsMap = contentsMap
```
