### ISSUE TITLE
2.9.0 release is missing a changelog and not available on mavencentral

### ISSUE THREAD

**Issue by ZacSweers** [chibatching/Kotpref#170]

**Comment by chibatching** [comment]
I added change log. Thanks.
https://github.com/chibatching/Kotpref/releases/tag/v2.9.0

**Comment by chibatching** [comment]
I asked Bintray support Jcenter issue.

**Comment by ZacSweers** [comment]
I saw that other issue about CI uploads not working. Why not upload once locally for now if that works so the release is available?

**Comment by chibatching** [comment]
I found the cause of this issue #169. 
Gradle parallelism cause invalid task execution order, and I fixed it on #171.

I released 2.9.1 with complete artifacts. Please use it.

**Comment by ZacSweers** [comment]
Updated and worked like a charm, thanks! https://github.com/ZacSweers/CatchUp/pull/174
