### ISSUE TITLE
What is the bast way to handle DropDownPreference integer values

### ISSUE THREAD

**Issue by NLLAPPS** [chibatching/Kotpref#176]
I have a DropDownPreference with integer values. Android needs string-array for values to be used and that crates an issue where I have to define preference model member as  `var myPref: String by stringPref`.

Is there a correct way of of accessing this preference apart from converting it to Int in my code?

**Comment by chibatching** [comment]
You can use pref value as the backing field of your value.

```kotlin
object Settings : KotprefModel() {
    private var internalMyPref: String by stringPref(key = "myPref")
    var myPref: Int
        get() = internalMyPref.toInt()
        set(value) {
            internalMyPref = value.toString()
        }
}
```

**Comment by NLLAPPS** [comment]
That's right. Thank you.

On October 21, 2019 12:57:13 AM UTC, Takao Chiba <notifications@github.com> wrote:

You can use pref value as the backing field of your value.

object Settings : KotprefModel() {
    private var internalMyPref: String by stringPref(key = "myPref")
    var myPref: Int
        get() = internalMyPref.toInt()
        set(value) {
            internalMyPref = value.toString()
        }
}

**Comment by NLLAPPS** [comment]
Hi again, I don't suppose there is way to do above and observe with live-data.
Because myPref have no delegation, I get "failed to get preference key, check property 'pref' is delegated to Kotpref.'

Am I correct?

**Comment by chibatching** [comment]
Hi,

You are correct. Currently, Kotpref can't observe directly with LiveData.
