### ISSUE TITLE
Enum support?

### ISSUE THREAD

**Issue by plackemacher** [chibatching/Kotpref#18]
Hey there! Was just browsing through possible libraries to use to simplify interactions with `SharedPreferences` while using Kotlin and found yours.

Are there any plans on supporting enum storage while allowing customization between storage as a string or an integer from an ordinal? If you already have something in the works, that's great. If not, I could gladly contribute support for it to this library.

**Comment by chibatching** [comment]
I don't have the plan to support enum.
I can't imagine how we use kotpref with enum. Please explain more detail or show sample code image. 

Thanks 😃

**Comment by plackemacher** [comment]
I made a pull request for you to see what changes I was thinking: #20
