### ISSUE TITLE
should beginBulkEdit be thread-safe?

### ISSUE THREAD

**Issue by Gohan** [chibatching/Kotpref#196]
I did not figure out, how is beginBulkEdit need to be use..

The case I think it could used:

Thread 1: bulkEdit
Thread 2: read previous value before bulkEdit is submit. to keep data right

should beginBulkEdit throw exeception when there is already in transaction?

**Comment by chibatching** [comment]
BulkEdit of Kotpref suppose that an alternative of preference editor, like below

```kotlin
val editor = preferences.editor()
editor.putString(key1, value1)
editor.putBoolean(key2, value2)
editor.apply()
```

It doesn't care thread currently, it may be not thread-safe now.
