### ISSUE TITLE
KotPref + applicationIdSuffix not working

### ISSUE THREAD

**Issue by muetzenflo** [chibatching/Kotpref#197]
Hi! I am in the process of adding multiple buildTypes to my project.
For the debug build, I set an applicationIdSuffix ".debug" like this:

```
debug {
    applicationIdSuffix ".debug"
    minifyEnabled false
    debuggable true
}
```

With this suffix in place KotPref is still working as normal except for Preferences in the PreferenceFragmentCompat class. Here is my KotPrefModel:

```
object SharedPrefsApp : KotprefModel() {

    override val kotprefName: String = context.getString(R.string.preference_file_name)

    /**
     * Preferences set in the [SettingsFragment]
     * Saved the users preference between light mode, dark mode and "decide by battery/system settings"
     */
    var darkMode by stringPref(context.getString(R.string.preference_dark_mode_default), R.string.preference_dark_mode_key)

}
```

All strings are defined in `/src/main/res/values/string.xml` only
As soon as I remove the applicationIdSuffix everything works as expected.
The `R.string.preference_file_name` is used consistently:

-  in the KotPrefModel 

- in the PreferenceScreen root (`android:key="@string/preference_file_name"`)

- whenever I want access to the SharedPreferences like this

```
val sharedPreferenceKey = androidContext().getString(R.string.preference_file_name)
context.getSharedPreferences(sharedPreferenceKey, Context.MODE_PRIVATE)
```

Do you have any idea what the applicationIdSuffix is triggering/changing so that only the `ListPreference` in the xml is not working anymore?

Thanks!

**Comment by chibatching** [comment]
Hi,

You should check this issue #47.

In summary, you should set the preference file name on PreferenceFramgment through `preferenceManager. sharedPreferencesName`.
`android:key` on PreferenceScreen doesn't affect file name.

**Comment by muetzenflo** [comment]
Damn, I used exactly this issue to set everything up, but it seems I just missed this line.
All working now. Thanks again for your quick response!!
