### ISSUE TITLE
Crash on latest library version if I compose delegates

### ISSUE THREAD

**Issue by andob** [chibatching/Kotpref#198]
If I import the latest version

```
implementation 'com.chibatching.kotpref:kotpref:2.10.0'
implementation 'com.chibatching.kotpref:gson-support:2.10.0'
```

And then

```
object AppPreferences : KotprefModel()
{
    var authToken : String? by nullableStringPref()
    var loggedInUser : User? by gsonNullablePref()
}
```

```
class App : Application()
{
    override fun onCreate()
    {
        super.onCreate()

        Kotpref.init(context)
        Kotpref.gson=GsonFactory.gson
    }
}
```

Each time I set or get the ``AppPreferences.loggedInUser`` field or the ``AppPreferences.authToken``, an exception is raised:

```
kotlin.UninitializedPropertyAccessException: lateinit property property has not been initialized
        at com.chibatching.kotpref.pref.AbstractPref.getPreferenceKey(AbstractPref.kt:22)
        at com.chibatching.kotpref.pref.StringNullablePref.getFromPreference(StringNullablePref.kt:15)
        at com.chibatching.kotpref.pref.StringNullablePref.getFromPreference(StringNullablePref.kt:8)
        at com.chibatching.kotpref.pref.AbstractPref.getValue(AbstractPref.kt:35)
        at com.chibatching.kotpref.pref.AbstractPref.getValue(AbstractPref.kt:9)
        at my_namespace.utils.preferences.AppPreferences.getAuthorization(AppPreferences.kt)
        at my_namespace.App$Companion.isUserLoggedIn(App.kt:42)
        at my_namespace.notifications.PushNotificationsClient.onNewToken(PushNotificationsClient.kt:20)
        at com.google.firebase.messaging.FirebaseMessagingService.zzc(com.google.firebase:firebase-messaging@@20.1.0:104)
        at com.google.firebase.messaging.zze.run(com.google.firebase:firebase-messaging@@20.1.0:2)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at com.google.android.gms.common.util.concurrent.zza.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:761)
```

If I downgrade to 2.9.2, it works fine.

**Comment by chibatching** [comment]
Hi,

I couldn't reproduce the issue.
Would you share your whole project reproducing that?

**Comment by andob** [comment]
Yes. [Here](https://drive.google.com/open?id=15jC0xVy_EdaFw27pUjreeKqVBT8WMDkz) is a project reproducing the bug.

I found the root cause of the bug. I'm basically using a caching delegate like this:

```
var loggedInUser : User? by cached(gsonNullablePref())
```

```
class CachedDelegate<R, T>
(
    private val delegate : ReadWriteProperty<R, T>
) : ReadWriteProperty<R, T>
{
    override fun getValue(thisRef : R, property : KProperty<*>): T
    {
        //if there is a value cached in RAM, return that value. or else...
        return delegate.getValue(thisRef, property)
    }

    override fun setValue(thisRef : R, property : KProperty<*>, value : T)
    {
        //set the value in RAM cache, then...
        delegate.setValue(thisRef, property, value)
    }
}

fun <R, T> cached(delegate : ReadWriteProperty<R, T>) = CachedDelegate(delegate)
```

The problem is that ``provideDelegate`` operator function doesn't get called on the ``gsonNullablePref`` delegate. If gets called only on ``CachedDelegate``. So if I..

```
class CachedDelegate<R, T>
(
    private val delegate : ReadWriteProperty<R, T>
) : ReadWriteProperty<R, T>
{
    operator fun provideDelegate(thisRef: R, property: KProperty<*>) : ReadWriteProperty<R, T>
    {
        (delegate as? AbstractPref<*>)?.provideDelegate(thisRef = thisRef as KotprefModel, property = property)
        return this
    }
.................
```

It will work fine..

**Comment by chibatching** [comment]
Yes. From 2.10.0 Kotpref uses `provideDelegate`

**Comment by andob** [comment]
ok. but what's the solution?
1. either to revert to the old way, and  stop using provideDelegate?
2. or to continue using provideDelegate and implement a similar RAM cache in kotpref? I am thinking about a by intPref(cachedInRam = true), by stringPref(cachedInRam = true) and so on, this cachedInRam argument would be optional and would default to false, so if I say by intPref(), it would not cache. The rationale of this cache is that some fields (authentication token, for instance) are read very often, so the app gains a little bit of performance by reading them from ram, if they exist in the cache, or from shared preferences otherwise.

**Comment by chibatching** [comment]
SharedPreferences Android implementation stores the value map of the preference on memory after loaded from XML.
I don't think Koptref does not need an additional cache mechanism.

**Comment by andob** [comment]
hmm. I didn't knew that 😅. I guess my cache is redundant in this context, so I'll stop using it.
Thanks.

**Comment by andob** [comment]
Hello again. I was curious so I did a little benchmark:

```
Auth token benchmark
Reading a string preference 100000 times
Kotpref + RAM cache: 1552 mills
Kotpref: 1460 mills
Vanilla: 1250 mills
```

As you can see, adding a RAM cache actually adds overhead, in the end the process takes longer.

```
User benchmark
Reading an object preference 100000 times
Kotpref + caching: 667 mills
Kotpref: 2068 mills
Vanilla: 1557 mills
```

Kotpref + RAM cache is faster only when used with gsonPref, but that's only because the GSON deserialization overhead is gone.
