### ISSUE TITLE
Add support for EncryptedSharedPreferences

### ISSUE THREAD

**Issue by ujavid** [chibatching/Kotpref#202]
API Level 23 supports encrypted shared preferences which is very easy to setup and use:
https://developer.android.com/reference/kotlin/androidx/security/crypto/EncryptedSharedPreferences.html

**Comment by chibatching** [comment]
There is a sample of integration with EncryptedSharedPreferences.
Please check https://github.com/chibatching/Kotpref/tree/master/sample/src/main/kotlin/com/chibatching/kotprefsample/encrypt

**Comment by ujavid** [comment]
Oh that's great! Thanks for the quick response!
