### ISSUE TITLE
Clear() does not work with EncryptedSharedPreferences

### ISSUE THREAD

**Issue by ujavid** [chibatching/Kotpref#203]
Calling model.clear() does not work if the model is backed by EncrypedSharedPreferences.

**Comment by chibatching** [comment]
I found the google official bug tracker issue that this problem.
https://issuetracker.google.com/issues/138314232

I'll check it later.

Thanks

**Comment by chibatching** [comment]
I found an appropriate issue ticket. 
https://issuetracker.google.com/issues/154366606.

It would happen because KotprefModel#clear() calls apply() of EncryptedSharedPreferences.
I think that the clear() method of Kotpref will work correctly if the bug of EncryptedSharedPreferences is fixed.

**Comment by ujavid** [comment]
:-1: thanks for the follow up!

**Comment by chibatching** [comment]
Fixed at latest EncryptedSharedPreferences
