### ISSUE TITLE
When mocking, the values are not initialized and mock returns default

### ISSUE THREAD

**Issue by waveduke** [chibatching/Kotpref#209]
Hi! I'm testing with Robolectric and when I create a mock of the file that holds my preferences, the values are not initialized and therefore returns the default values instead of my mock values.

## Example:
```kotlin
val preferences:Preferences = mockk() //Using Mockk

every { preferences.fingerprint } returns "Fingerprint"

assertEquals("Fingerprint", preferences.fingerprint) //Returns assertion error since value is ""
```

## At Preferences:

```kotlin
class Preferences(context, preferencesProvider) : KotprefModel(context, preferencesProvider){

    var fingerprint by stringPref()

}
```

**Comment by chibatching** [comment]
Hi @waveduke ,

I tried to reproduce it but I couldn't.
Would you share the entire reproducible project with me?

**Comment by waveduke** [comment]
Hi! I'm sorry about the question. 

It turns out that I was using the preferences class with an additional interface and I was mocking the preferences class, not the interface.

That made (I don't know why) the lazy value unavailable for the mock, even declaring it.

I just mocked the interface directly instead of the preferences class and everything works great! 

Thanks for your time and sorry for the misunderstanding.

Love this library :)
