### ISSUE TITLE
Commit changes

### ISSUE THREAD

**Issue by Miha-x64** [chibatching/Kotpref#21]
Hello. Thank you for a great library!

I need a way to `commit()` some changes instead of `apply()`ing them to save some crash information and exit immediately in my uncaught exception handler.

Here is my implementation: https://github.com/chibatching/Kotpref/pull/22

**Comment by Miha-x64** [comment]
While not released, we can rename `immediateBulk` to `blockingBulk` or `synchronousBulk` so people will think not "it's fast" but "it's blocking" and don't misuse it.

**Comment by chibatching** [comment]
Oh right, I agree with you! Would you rename and pull request?

**Comment by chibatching** [comment]
I prefer `synchronousBulk` :)

**Comment by chibatching** [comment]
I changed mind, I think that `blockingBulk` is more appropriate.
Sorry for backtracking and thank you suggestion!

**Comment by Miha-x64** [comment]
Done. #24
