### ISSUE TITLE
LiveData - fires twice upon first subscription

### ISSUE THREAD

**Issue by MFlisar** [chibatching/Kotpref#223]
I think following line should be changed:

https://github.com/chibatching/Kotpref/blob/44a921a9a9110cbbb956637028b51e30ae413bd5/livedata-support/src/main/kotlin/com/chibatching/kotpref/livedata/KotprefLiveDataExtensions.kt#L14

To following:

    value = property.get()

This will initialise the internal value. The `LiveData` object itself will emit this initial state upon subscription. Your solution will emit the initial state twice.

**Comment by chibatching** [comment]
Hi!
Thank you for reporting! I'll fix it!
