### ISSUE TITLE
Change value type

### ISSUE THREAD

**Issue by AliKhoshraftar** [chibatching/Kotpref#238]
Is there anyway to change stored preference type ?
I stored a value as intPref and now wanna change it to longPref.
But it crashes when i do it.

**Comment by chibatching** [comment]
Because `SharedPreferences` keep value with type info if you read the value as a different type, `SharedPreferences` throw ClassCastException.
If you have the definition KotprefModel like below

```kotlin
object Sample : KotprefModel() {
    var foo by intPref()
}
```

I recommend writing the migration code.

```kotlin
object Sample : KotprefModel() {
    var _foo by longPref(key = "foo")
    var foo: Long
        get() = try {
            _foo
        } catch (e: ClassCastException) {
            preferences.getInt(getPrefKey(::_foo), 0).toLong()
        }
        set(value) {
            _foo = value
        }
}
```
