### ISSUE TITLE
If a key is composed of fixed + dynamic parts, what to do？

### ISSUE THREAD

**Issue by EspoirX** [chibatching/Kotpref#246]
If a key is composed of fixed + dynamic parts, what to do？

for example： A color configuration needs to be stored along with the userId
At this time, the key is like this： KEY_COLOR_123，KEY_COLOR_456，KEY_COLOR_789 etc.（The number is userId, which is obtained dynamically）

**Comment by chibatching** [comment]
Kotpref doesn't support this usecase. Please use SharedPreferences directly.

**Comment by EspoirX** [comment]
Unfortunately, this case is very common after all
