### ISSUE TITLE
Unable to resolve dependency

### ISSUE THREAD

**Issue by Miha-x64** [chibatching/Kotpref#26]
Hello.
Gradle was unable to download `com.chibatching.pref:pref:2.0.0` for me. changing to `com.chibatching.kotpref:kotpref:2.0.0` helped. Have not checked whether other modules of library act like this or not.
http://jcenter.bintray.com/com/chibatching/kotpref/kotpref/2.0.0/

**Comment by chibatching** [comment]
Thanks, it's typo in README. You are correct!
I'll fix it later!
