### ISSUE TITLE
StringSetPref iterator

### ISSUE THREAD

**Issue by Miha-x64** [chibatching/Kotpref#28]
Hello.
I've noticed that all mutating operations on a set are being applied immediately, e. g.
```
val result = set.add(element)
kotprefModel.kotprefPreference.edit().putStringSet(key, set).apply()
return result
```
but `iterator()` funciton just returns undecorated `set.iterator()`, and it's easy to call `remove()` on it without triggering SharedPreferences update.
Am I right? Will this be fixed? Do you need help with it?

**Comment by chibatching** [comment]
Thank you for your reporting.
You are right. Currently, `StringPrefSet` doesn't override `iterator` method.
I should it, and I'll fix this.

Thanks! 😄

**Comment by chibatching** [comment]
I tried to fix this. 
But I found that it's too hard to support remove on iterator for me.
I'll just throw the UnsupportedOperationException when execute remove operation on iterator.

Sorry.

**Comment by Miha-x64** [comment]
Hey, it's nothing to be sorry about! Walking on the edge of technology is quirky, we all being stuck sometimes. :)
Throwing an exception is definitely better than the old behavior.
I'll also try to implement `remove()`, but not just now. (I am at work.)

**Comment by chibatching** [comment]
I merged the fix by throwing an exception. But I'm looking forward to good news from you! :)

**Comment by Miha-x64** [comment]
My idea is just to write in StringSetPref.kt
```kt
137:  baseIterator.remove()
138:  kotprefModel.kotprefPreference.edit().putStringSet(key, set).apply()
```
but I'm unable to check whether it works: I'm unable to run StringSetPrefTest, getting `android.content.res.Resources$NotFoundException: String resource ID #0x7f020002`. I think the problem may be in `setResourceDir("../../../../../src/${BuildConfig.BUILD_TYPE}/res")`, but I don't know it exactly and not familiar with Robolectric.

**Comment by chibatching** [comment]
You should set working directory `$MODULE_DIR$` at JUnit run configuration to work robolectric test properly.

I tried it, but it can't work well in bulk edit. But I found solution like below!

```kotlin
baseIterator.remove()
if (inTransaction) {
    kotprefModel.kotprefEditor!!.putStringSet(key, transactionData, this@PrefMutableSet)
} else {
    kotprefModel.kotprefPreference.edit().putStringSet(key, set).apply()
}
```

Thanks! :)

**Comment by Miha-x64** [comment]
While in transaction, why are you putting updated set on each deletion? Returning `transactionData!!.iterator()` would be fine, because after some `remove()` invocations we're going to commit a transaction manually.

**Comment by chibatching** [comment]
Currently, We should set edited value to KotprefEditor (`SharedPreferences#Editor` wrapper) in transaction.
When bulk edit block ended, Kotpref will commit/apply KotprefEditor's values. 

But, current implementation is not efficient. I'll improve it.
