### ISSUE TITLE
dynamic preferences

### ISSUE THREAD

**Issue by yoavst** [chibatching/Kotpref#3]
Maybe adding something like that to `KotprefModel`:
```kotlin
publlic fun set(field: String, supportedType: SupportedTypeComesHere) {
  ...
}
```
and a get for each type.

**Comment by chibatching** [comment]
When do you use this function?
I have not come to mind about use cases.

**Comment by yoavst** [comment]
I've find that you can access the underlay sharedPreferences object, so you can close it I think. Also, I've got a problem with the set (added string was not added).
