### ISSUE TITLE
Expose a way to add a listener to preferences

### ISSUE THREAD

**Issue by davidwhitman** [chibatching/Kotpref#48]
Adding a listener so something can be notified when a preference is changed seems like common behavior, but I can't find a way to do so easily.

The `SharedPreferences` instance is internal to `KotPrefModel`, so using `OnSharedPreferenceChangeListener` requires actually getting the sharedPrefs object based on the class name, which you'd need to calculate yourself or hardcode.

Exposing the `sharedPreferences` object in `KotprefModel` would be an easy solution to this. Another would be writing your own wrapper for listeners.

**Comment by kirtan403** [comment]
+1 to this feature. A much needed one. Would be waiting for this

**Comment by chibatching** [comment]
New release v2.2.0, shared preferences is exposed.

You can now access the SharedPreferences instance for your KotprefModel.

```kotlin
object Sample : KotprefModel {
   ...
}

fun setSharedPreferencesListener() {
   Sample.preferences.registerOnSharedPreferenceChangeListener { sp, key ->
       // ...
   }
}
```

**Comment by kirtan403** [comment]
Awesome! +1 for this
