### ISSUE TITLE
Will it support encryption?

### ISSUE THREAD

**Issue by fly7632785** [chibatching/Kotpref#72]
Hi, this is a great open library
but, will it support encryption?
That must be better

**Comment by chibatching** [comment]
I have no plan to support encryption.
But I used with other encryption library (https://github.com/gfx/Android-EncryptUtils) in production code.

**Example**
```kotlin
object EncryptedData : KotprefModel() {

    private val encryption = Encryption(Encryption.getDefaultCipher(), byteArrayOf(...))
    
    private var encryptedFoo by stringPref("")

    fun getFoo(): String =
            if (encryptedFoo.isEmpty()) {
                ""
            } else {
                encryption.decrypt(encryptedFoo)
            }

    fun setFoo(foo: String) {
        if (foo.isNotEmpty()) {
            encryptedFoo = encryption.encrypt(foo)
        }
    }
}
```

I think that you can use any other library you want.

**Comment by fly7632785** [comment]
Thanks, I will look at it

**Comment by fly7632785** [comment]
But, if I use this library to encrypt. How can I encrypt the Object, is there any interface to operate the gson string? Please and thank you

**Comment by fly7632785** [comment]
And @chibatching 
May I fork your library and add a encryption support?
Hope to communicate with you in the spect of tech

**Comment by chibatching** [comment]
Of course it's ok, but I will try to create interface to inject custom converter (e.g. #42) to Kotpref at next major version.
This may possibly stop developing and remove some optional support artifact (like gson, enum support) from this repo.

**Comment by fly7632785** [comment]
Well, good
I've forked it 
[Kotpref](https://github.com/fly7632785/Kotpref)
 and make a support library of Encryption
[KotprefEncryptSupport](https://github.com/fly7632785/KotprefEncryptSupport)
Hope to get your suggestion about it.
And thank you,Your Kotpref is a good lib.
Custom converter is a good idea,
I will stay focused on it
