### ISSUE TITLE
Support for double

### ISSUE THREAD

**Issue by limpep** [chibatching/Kotpref#91]
Hi would it be possible to add support for double data type?

**Comment by chibatching** [comment]
SharedPreferences doesn't support double. If we want to save double value, we have to convert other type.

Appropriate conversion type is dependent on your usecase. (precision, efficiency...)
So, I'll not support it by this library.
I recommend you implement your own converting like below simple double to string conversion.

```kotlin
object DoubleToStringExample : KotprefModel() {
    private var convertedDouble by stringPref()

    var doubleValue: Double
        get() = convertedDouble.toDouble()
        set(value) {
            convertedDouble = value.toString()
        }
}
```

**Comment by limpep** [comment]
I didn't realise that double wasn't supported. Thanks I'll look into the approach you mentioned.
